### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by Suntrie** [Foxilyan/JavaClass#2]
1. Если у Вас есть ограниченное подмножество значений, вариантов 2 - завести enum/ public static final строки (если что-то повторяется в коде много раз, лучше завести именованную константу, намного проще будет править). Первый вариант предпочтителен с точки зрения организации кода;
2. fieldSize действительно может быть любым? (видимо, стоит добавить чекер и выбрасывать исключение, если что-то пошло не так, поскольку речь идёт о конструкторе; для сеттеров тоже стоит посмотреть);
3. Для методов типа set/remove стоит завести возвращаемый результат типа boolean. Программисту, использующему Ваш код, должно быть понятно, успешно или нет отработал метод;
4. Логика findLongest пока не до конца ясна, а хороший код, по идее, должен быть самодокументированным. Стоит подумать о выделении повторяющейся логики во вспомогательные (приватные) методы с говорящими именами. Кроме этого, максимум может быть и по диагонали.

**Comment by Foxilyan** [comment]
По поводу пункта 4
Логика такая: если в клетке подходящий символ, то проверяем, с какой стороны идет последовательность (сверху up, слева left или по диагонали dia). Если принадлежит нескольким последовательностям, берем ту, которая длиннее. Если не принадлежит никакой, значит 1ый символ последовательности. В копию поля ставим числовые значения порядкового номера элемента последовательности (0 если пустая или не тот символ)

Диагональ у меня обрабатывается, но только слева-сверху вниз-направо. Добавлю проверку второй диагонали сверху-справа вниз налево, код подправлю, там можно, собственно, проверку направления в отельный метод засунуть

Спасибо большое за комментарии, буду доделывать

**Comment by Suntrie** [comment]
5. Добавьте, пожалуйста, override equals, toString, hashCode.

**Comment by Suntrie** [comment]
> Логика такая: если в клетке подходящий символ, то проверяем, с какой стороны идет последовательность (сверху up, слева left или по диагонали dia). Если принадлежит нескольким последовательностям, берем ту, которая длиннее. Если не принадлежит никакой, значит 1ый символ последовательности. В копию поля ставим числовые значения порядкового номера элемента последовательности (0 если пустая или не тот символ)

При попытке порисовать вроде бы выходит, что первая строка и остальные обрабатываются несколько по-разному. Для этого метода стоит добавить больше тестов, ориентируясь [на покрытие](https://www.jetbrains.com/help/idea/running-test-with-coverage.html). В норме, код для первого задания должен быть покрыт тестами на 80+%

**Comment by Suntrie** [comment]
Большая часть комментариев (за исключением 5) закрыта, issues переехали в соседний проект.
